### ISSUE TITLE
Only One 3090

### ISSUE THREAD

**Issue by mumuyeye** [xpq-tech/PMET#1]
Could you please tell me only one 3090 can run this program？I can't solve this problem.When I change to float16,I still can not run this program.Please help me.

**Comment by xpq-tech** [comment]
Sorry, you cannot run this program with just one 3090. You may need to ask for A100/A800 GPUs to your BOSS to run it.

**Comment by nicerghe** [comment]
> Sorry, you cannot run this program with just one 3090. You may need to ask for A100/A800 GPUs to your BOSS to run it.

Can a single A800 GPU support GPT-J --num_edits=10000 execution?

**Comment by xpq-tech** [comment]
> > Sorry, you cannot run this program with just one 3090. You may need to ask for A100/A800 GPUs to your BOSS to run it.
> 
> Can a single A800 GPU support GPT-J --num_edits=10000 execution?

yes
