### ISSUE TITLE
FileNotFoundError: Couldn't find a dataset script at /path/to/PMET/edit/caches/wikipedia.py

### ISSUE THREAD

**Issue by HLiang-Lee** [xpq-tech/PMET#2]
同学你好，PMET是一篇非常nice的工作。我在复现PMET效果时遇到如下报错：
`FileNotFoundError: Couldn't find a dataset script at /path/toPMET/edit/caches/wikipedia.py
`
请问我可以到哪里下载到上述文件？很期待您的帮助～非常感谢！

**Comment by xpq-tech** [comment]
抱歉，由于网络原因，之前经常会出现wikipedia.py下载失败的问题，所以我自己下载了该脚本然后以本地文件的形式加载，现在我已经修复了代码，采用最新的代码在网络允许的情况下应该会自动下载不会再出现这样的问题，或者直接从https://huggingface.co/datasets/wikipedia/blob/main/wikipedia.py下载该脚本。
