### ISSUE TITLE
10K edits怎么取呢？

### ISSUE THREAD

**Issue by XZhang00** [xpq-tech/PMET#3]
您好！非常感谢您为PMET开源的代码，这是一篇很好的工作！
想问一下在复现表1的结果时，这10000个edits怎么取呢？是直接取前10000个吗？还是说只是用batch=10000的setting对multicounterfact数据集中的全部数据进行编辑，然后计算在全部数据上的指标的平均值呢？
期待您的解答！非常感谢您的帮助～

**Comment by xpq-tech** [comment]
感谢您对我们的工作的关注！是用batch=10000的setting对multicounterfact数据集中的全部数据进行编辑，然后计算在全部数据上的指标的平均值.

**Comment by XZhang00** [comment]
非常感谢您的解答！
