### ISSUE TITLE
wikipedia下载时遇到问题

### ISSUE THREAD

**Issue by CuSO4-Chen** [xpq-tech/PMET#4]
作者您好，非常感谢您开源的代码以及优秀的研究工作，我在复现PMET效果时遇到如下问题：
    def get_ds():
        # Load_From_File
        # from datasets import Dataset
        # raw_ds = Dataset.from_file('XXX/XXX/wikipedia-train.arrow')
        # raw_ds = {'train': raw_ds}

        raw_ds = load_dataset(
            ds_name,
            dict(wikitext="wikitext-103-raw-v1", wikipedia="20200501.en")[ds_name],
        )
报错ConnectionError，可能是我服务器网络的问题。然后我尝试在本地下载该数据，想请教如下两个问题：
（1）上述代码试图访问一个python文件，我可以将wikipedia.py文件存在服务器上，但请问应当如何修改这段代码？
（2）在本地下载数据时发生报错，不存在wikipedia="20200501.en"，似乎仅能选择20220301，请问应该如何解决？
非常期待您的帮助～非常感谢！

**Comment by CuSO4-Chen** [comment]
问题（1）已经解决，谢谢~

**Comment by xpq-tech** [comment]
感谢您对我们工作的关注！问题（2）我提供的源代码是wikipedia="20220301.en"，所以使用这个即可。wikipedia="20200501.en"不存在是因为huggingface上还未提供20200501数据，https://huggingface.co/datasets/wikipedia 这个链接中可以访问到的应该都是能下载的。

**Comment by CuSO4-Chen** [comment]
非常感谢您的回复，抱歉我的代码来源于EasyEdit处集成的您的代码，那边仍然选择了20200501数据，您的代码解决了我的问题。但我想请教一下，不同的wikipedia数据是否会对实验结果产生比较大的影响呢？期待您的回复，非常感谢~

**Comment by xpq-tech** [comment]
应该不会产生很大影响。

**Comment by CuSO4-Chen** [comment]
明白了，非常感谢您的回复，祝一切顺利
